
# Problem Statement

## Effective Prompt Design in GPT

At Healthcare Innovations Inc., we’re dedicated to improving healthcare delivery in the commercial sector by combining technology with patient-centered care. Since 2010, we’ve worked with healthcare providers, insurers, and pharma organizations to streamline workflows, enhance patient engagement, and drive better outcomes through innovative solutions like telemedicine, personalized tools, and data analytics.

Our goal is simple: to make healthcare more accessible, efficient, and focused on the needs of patients. With a team of experts across medicine, tech, and business, we’re committed to transforming healthcare and improving lives, one solution at a time.


Prompt Engineering: It refers to the practice of designing and refining the input prompts given to AI models, such as language models, in order to elicit specific, useful, and accurate responses. The goal is to frame the prompt in a way that guides the AI to generate the desired outcome, whether it’s answering a question, writing content, solving a problem, or performing a task.

### Objectives
Effective prompt design aims to provide clear, concise instructions that guide users toward accurate inputs, ensuring smooth interaction, adaptability, and clarity for achieving desired outcomes.

## Data Description

### Dataset Overview
The dataset contains patient information and visit records from healthcare providers. Below is a description of each column in the dataset:

- HCP_ID: Unique identifier for each healthcare professional (HCP).
- Name: Full name of the healthcare professional.
- Specialty: Medical specialty or area of expertise of the healthcare professional (e.g., Cardiology, Pediatrics).
- Location: The geographical location of the healthcare professional's practice (e.g., City, State).
- Hospital_Affiliation: The name of the hospital or healthcare institution the professional is affiliated with.
- Years_of_Experience: The number of years the healthcare professional has been practicing in their specialty.
- Patient_Count: The number of patients the healthcare professional is currently seeing or has seen in a certain period.
- Engagement_Score: A score representing the level of engagement or interaction of the healthcare professional with the organization or brand.
- Email: Email address of the healthcare professional.
- Phone_Number: Contact phone number of the healthcare professional.
- Last_Interaction_Date: The date of the most recent interaction or communication with the healthcare professional.
- Preferred_Contact_Method: The preferred method of contact for the healthcare professional (e.g., Email, Phone, In-person).
- Compliance_Flag: A flag indicating whether the healthcare professional is compliant with relevant standards or regulations (e.g., Yes/No, True/False).
- Associated_Brand: The name of the brand or company associated with the healthcare professional, if applicable.
- Region: The geographical region in which the healthcare professional practices or is located (e.g., North America, Europe).

In [7]:
# Importing Necessary Liberaries

from langchain_openai import ChatOpenAI
import os
from langchain_community.document_loaders.csv_loader import CSVLoader
import pandas as pd 
import numpy as np
from langchain.prompts import PromptTemplate
from langchain.schema.output_parser import StrOutputParser

## Step 1: Data Preprocessing

### Explanation:
- Purpose: Setting up Large Language Model and Loading up dataset
  
### Steps:
1: Setting the OpenAI API Key and Initializing the Chat Model
- Set API Key: Configure your OpenAI API key as an environment variable to authenticate requests.
- Initialize Model: Create a ChatOpenAI object to interact with GPT-4, enabling the sending and receiving of prompts and responses.

2: Reading Data from a CSV File
- Read CSV: Use pandas to load data from the CSV file (synthetic_hcp_data_10k.csv) into a DataFrame (data).
- Data Access: This allows you to manipulate and analyze the structured data easily.

3: Defining a Function to Retrieve Specific Data
- Define Function: Create a function (get_HCP_data) to filter the DataFrame based on specific conditions (e.g., matching Name and Email columns).
- Return Data: The function returns the subset of data corresponding to the provided name and email.

Setting up ChatGpt Model
- Configures the API key for authentication (you can refer this documentation for getting new api key and understanding how to make openai API calls https://platform.openai.com/docs/quickstart?language-preference=python)

In [ ]:
os.environ['OPENAI_API_KEY']= "your_api_key"
llm=ChatOpenAI(model="gpt-4o")

Loading the Data

In [9]:
file_path = "synthetic_hcp_data_10k.csv"

data = pd.read_csv(file_path)
data.head(5)

,HCP_ID,Name,Specialty,Location,Hospital_Affiliation,Years_of_Experience,Patient_Count,Engagement_Score,Email,Phone_Number,Last_Interaction_Date,Preferred_Contact_Method,Compliance_Flag,Associated_Brand,Region
0,f93053a8-61f0-4789-b3c6-7ddc9d830e25,Albert Jones,Neurology,Higginsville,Rhodes Inc,38,964,0.71,jerry19@yahoo.com,+1-083-768-2335x11893,2024-01-20,Phone,False,Brand_B,South
1,973693f7-aeb8-436b-91be-38b82f1a6dd4,Duane Smith,Dermatology,South Robert,Wagner-Johnson,34,660,0.13,marklopez@gmail.com,4682321697,2024-01-07,Phone,False,Brand_D,North
2,433409c2-7bf8-4e9f-89af-47b8cb9b7264,Jeffrey Larsen,Cardiology,New Lindaland,Wade-Thompson,28,766,1.00,michaelwood@trevino-greene.com,+1-700-994-1183x8590,2024-07-21,Email,False,Brand_C,North
3,1c4edd5a-3232-438b-809a-ec56f1fce706,Peter Lewis,Cardiology,Floydport,Campbell-Johnson,4,898,0.34,robert27@gonzalez-benjamin.info,001-627-300-0235,2024-05-10,Phone,True,Brand_A,West
4,bab9dd95-d062-45b6-a0e4-238ab29b969c,Stephanie Christensen,Cardiology,Matthewhaven,Coleman-Kane,15,341,0.47,larry21@hotmail.com,656.042.7240,2024-11-18,In-Person,False,Brand_C,South

Defining a Function to Retrieve Specific Data

In [10]:
def get_HCP_data(doc_name, doc_email):
    doc_data = data[(data['Name'] == doc_name) & (data['Email'] == doc_email)]
    return doc_data

get_HCP_data("Albert Jones", "jerry19@yahoo.com")

,HCP_ID,Name,Specialty,Location,Hospital_Affiliation,Years_of_Experience,Patient_Count,Engagement_Score,Email,Phone_Number,Last_Interaction_Date,Preferred_Contact_Method,Compliance_Flag,Associated_Brand,Region
0,f93053a8-61f0-4789-b3c6-7ddc9d830e25,Albert Jones,Neurology,Higginsville,Rhodes Inc,38,964,0.71,jerry19@yahoo.com,+1-083-768-2335x11893,2024-01-20,Phone,False,Brand_B,South

## Steps:
### 1. Define Email Drafting Process:
- Create a template for an email to invite healthcare providers to a webinar, using placeholders like {doctor_information} and provide styling for response for dynamic content.
### 2. Basic Email Generation:
- Generate the email by invoking the model chain with the basic template and relevant doctor details.
### 3. Enhance Email with Context:
- Expand the template with additional context about the company, ensuring professionalism and compliance.
### 4. Zero-Shot Learning:
- Use the model in a zero-shot setting to generate an email without specific examples, guided by provided context.
### 5. Chain of Thought Email Drafting:
- Break down the email drafting process into structured steps (objective, recipient, compliance, effectiveness) to guide the model.
### 6. Few-Shot Learning:
- Include example emails in the template to guide the model on structure, tone, and language for generating compliant emails.

### Step 1
#### Create a simple template that outlines the task, instructing the model to write an email to a healthcare provider about an upcoming webinar on a new drug.
### Example 1

In [11]:
template = """
Write an email to a healthcare provider about an upcoming webinar on a new drug. 
"""

chain = llm | StrOutputParser()

result = chain.invoke(template)

print(result)

Subject: Invitation to Upcoming Webinar: Exploring the Latest Breakthrough in [Drug Name] Development

Dear [Healthcare Provider's Name],

I hope this message finds you well. We are excited to invite you to an upcoming webinar that will provide an in-depth exploration of the newly developed drug, [Drug Name], which promises to be a significant advancement in the field of [relevant medical field or condition].

**Webinar Details:**

- **Topic:** Understanding the Innovations and Implications of [Drug Name]
- **Date:** [Date]
- **Time:** [Time] [Time Zone]
- **Duration:** [Duration]
- **Platform:** [Platform Name] (Link to be provided upon registration)

During this session, our panel of experts will discuss:

- The research and development journey of [Drug Name]
- Clinical trial outcomes and safety profile
- Mechanism of action and therapeutic potential
- Practical applications and case studies
- Q&A session to address your inquiries

We believe this webinar will be highly beneficial for healthcare professionals seeking to stay informed about the latest advancements in treatment options for [relevant condition]. Your expertise and insight would greatly enrich the discussion, and we would be honored to have you join us.

Please register for the webinar by clicking on the following link: [Registration Link]

If you have any questions or require further information, feel free to contact us at [Contact Information]. We look forward to your participation in this informative event.

Thank you for your dedication to advancing healthcare through continuous learning and innovation.

Warm regards,

[Your Full Name]
[Your Position]
[Your Contact Information]
[Organization/Company Name]

[Optional attachment: brochure or flyer for the webinar]

### Step 1: Example 2

In [12]:
template = """
Write an email to a healthcare provider about an upcoming webinar on a new drug. 
"""

chain = llm | StrOutputParser()

result = chain.invoke(template)

print(result)

Subject: Invitation to Upcoming Webinar on [Drug Name]: A Breakthrough in Treatment

Dear [Healthcare Provider's Name],

I hope this message finds you well. I am writing to invite you to an upcoming webinar that we believe will be of great interest to you and your practice. We are hosting an informative session on [Drug Name], a new and innovative treatment option for [specific condition or disease], which has recently been approved by [relevant authority, e.g., FDA].

**Webinar Details:**

- **Title:** Exploring [Drug Name]: Transforming Treatment for [Condition]
- **Date:** [Date]
- **Time:** [Time] [Time Zone]
- **Duration:** [Duration]
- **Platform:** [Platform, e.g., Zoom, Webex]

During this webinar, our panel of experts will cover:

- The mechanism of action and clinical benefits of [Drug Name].
- Results from recent clinical trials.
- Patient selection criteria and potential side effects.
- Practical guidance on incorporating [Drug Name] into your treatment protocols.

The session will be followed by a Q&A segment, allowing you to engage directly with our experts and address any questions or concerns you may have.

**How to Register:**

Please register for the webinar by clicking on the following link: [Registration Link]. After registering, you will receive a confirmation email with further details on joining the webinar.

We are excited about the potential of [Drug Name] to improve patient outcomes and are eager to share this information with professionals like yourself who are at the forefront of patient care.

Thank you for considering this opportunity to enhance your knowledge and practice. If you have any questions regarding the webinar, please feel free to contact me directly at [Your Contact Information].

Looking forward to your participation.

Warm regards,

[Your Full Name]
[Your Position]
[Your Organization]
[Contact Information]
[Organization's Website]

---

### Step 1: Example 3: Styling

In [13]:
template = """
Write an email to a healthcare provider about an upcoming webinar on a new drug.
Make email more formal """
 
 
chain = llm | StrOutputParser()
 
result = chain.invoke(template)
 
print(result)

Subject: Invitation to Attend an Upcoming Webinar on [Drug Name]: Innovations in Healthcare

Dear [Healthcare Provider's Name],

I hope this message finds you well. I am writing to formally invite you to an upcoming webinar that promises to be both informative and engaging, focusing on the latest advancements in pharmaceutical innovation—specifically, the introduction of [Drug Name], a groundbreaking new treatment in [relevant therapeutic area].

This webinar, titled "[Webinar Title]," is scheduled to take place on [Date] at [Time], and will be hosted via [Platform, e.g., Zoom, Microsoft Teams]. During this session, esteemed experts in the field will provide comprehensive insights into the development, clinical trials, and anticipated impact of [Drug Name] on patient care.

Key topics to be discussed include:
- The pharmacological profile and mechanism of action of [Drug Name].
- Clinical trial outcomes and efficacy data.
- Safety and tolerability profiles.
- Potential applications in clinical practice.

This event represents a valuable opportunity to enhance your understanding of [Drug Name] and to engage with leading professionals in the field. We are confident that the knowledge shared during this webinar will be of great benefit to your practice and your patients.

To confirm your participation, please register at your earliest convenience by clicking on the following link: [Registration Link]. Upon registration, you will receive a confirmation email with details on how to join the webinar.

Should you have any questions or require further information, please do not hesitate to contact me directly at [Your Email Address] or [Your Phone Number].

Thank you for considering this invitation. We look forward to your participation in what promises to be a highly enlightening session.

Warm regards,

[Your Full Name]
[Your Position]
[Your Organization]
[Your Contact Information]

### Step 2:  Example 1
#### Using the basic template, an email is generated by invoking the model chain. The model generates the email content based on the template and context passed in the doctor_information.

In [14]:
doc_name = "Albert Jones"

doc_email = "jerry19@yahoo.com"

template = """
You are drafting an email for a sales representative in a healthcare company. 
The goal is to invite a healthcare provider to an educational webinar on a newly FDA-approved drug for diabetes management. 
The tone should be professional, compliant, and informative.
{doctor_information}
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Invitation to Exclusive Webinar on the Latest Advances in Diabetes Management

Dear Dr. Jones,

I hope this message finds you well.

I am writing to personally invite you to an upcoming educational webinar hosted by [Your Healthcare Company Name]. This online event will cover the latest advancements in diabetes management, featuring a newly FDA-approved drug that shows promise in improving patient outcomes.

**Webinar Details:**

- **Topic:** Innovations in Diabetes Treatment: Understanding the Impact of [Drug Name]
- **Date:** [Insert Date]
- **Time:** [Insert Time]
- **Duration:** [Insert Duration]
- **Platform:** [Insert Platform]

As a healthcare provider with extensive experience and expertise, your participation would be invaluable. The session will provide insights into the drug’s mechanism of action, clinical trial results, and its potential benefits for patient care. You will also have the opportunity to engage with industry experts and ask questions.

Please let us know your availability by [RSVP Deadline]. You can register for the webinar using the following link: [Insert Registration Link].

If you have any questions or require further information, feel free to reach out to me directly at [Your Contact Information].

Thank you for considering this invitation. We look forward to your participation and the valuable perspective you bring to the field of diabetes management.

Warm regards,

[Your Full Name]
[Your Job Title]
[Your Healthcare Company Name]
[Your Contact Information]
[Your Company’s Website URL]

P.S. If you prefer to discuss this invitation over the phone, please let me know, and I will be happy to arrange a call at your convenience.

### Step 2: Example 2:

In [15]:
doc_name = "John Pittman"

doc_email = "twilkinson@hotmail.com"

template = """
You are drafting an email for a sales representative in a healthcare company. 
The goal is to invite a healthcare provider to an educational webinar on a newly FDA-approved drug for diabetes management. 
The tone should be professional, compliant, and informative.
{doctor_information}
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Invitation to Exclusive Webinar on New Diabetes Management Drug

Dear Dr. John Pittman,

I hope this message finds you well. My name is [Your Name], and I am a sales representative at [Your Company]. We are excited to invite you to an exclusive educational webinar on an innovative new drug for diabetes management, recently approved by the FDA.

As a leading professional in the healthcare industry with extensive experience, we believe your insights and expertise would greatly contribute to the discussion. This webinar will cover the drug's mechanism of action, clinical trial outcomes, and its potential impact on patient care. It will also provide an opportunity to engage with experts and peers in the field.

**Webinar Details:**
- **Date:** [Insert Date]
- **Time:** [Insert Time]
- **Duration:** [Insert Duration]
- **Platform:** [Insert Platform]

To confirm your attendance, please register using the link below:
[Insert Registration Link]

Your participation would be highly valued, and we are keen to share this groundbreaking development with you. If you have any questions or need further information, please feel free to reach out to me directly at [Your Contact Information].

Thank you for considering this opportunity to enhance your knowledge and connect with fellow healthcare professionals. We look forward to your participation.

Warm regards,

[Your Full Name]
[Your Position]
[Your Company]
[Your Contact Information]

Please note: This email is intended for healthcare professionals only and is compliant with all applicable regulations.

### Step 3: Example 1
#### Zero-Shot Model Application: The model is used in a zero-shot setting, where it generates an email without having specific examples to learn from. The email is created using the same template but guided by additional context about the company’s mission, the email’s goal, and the tone to use.

In [16]:
doc_name = "Albert Jones"

doc_email = "jerry19@yahoo.com"

template = """
At Healthcare Innovations Inc., we’re dedicated to improving healthcare delivery in the commercial sector by combining technology with patient-centered care. 
Since 2010, we’ve worked with healthcare providers, insurers, and pharma organizations to streamline workflows, enhance patient engagement, and drive better outcomes through innovative solutions like telemedicine, personalized tools, and data analytics. 
Our goal is simple: to make healthcare more accessible, efficient, and focused on the needs of patients. With a team of experts across medicine, tech, and business, we’re committed to transforming healthcare and improving lives, one solution at a time.
You are drafting an email for a sales representative in a healthcare company. 
The goal is to invite a healthcare provider to an educational webinar on a newly FDA-approved drug for diabetes management. 
The tone should be professional, compliant, and informative.

NOTE: Do not give Webinar Details. give the doctor name as the sender name 
{doctor_information}
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Invitation to Educational Webinar on a Newly FDA-Approved Diabetes Drug

Dear Dr. Jones,

I hope this message finds you well. My name is Albert Jones, and I am a sales representative at Healthcare Innovations Inc. We are dedicated to enhancing healthcare delivery by integrating cutting-edge technology with patient-centered care.

I am reaching out to invite you to an exclusive educational webinar that will introduce a newly FDA-approved drug for diabetes management. This session is designed to provide valuable insights into the drug's efficacy, safety profile, and its potential to improve patient outcomes in diabetes care.

As a healthcare provider committed to delivering the best possible care to your patients, I believe this webinar could offer significant benefits to your practice. Our team of experts will be available to answer any questions you may have and discuss how this new treatment option can be integrated into your current diabetes management protocols.

Please let me know if you are interested in attending, and I will ensure that you receive all necessary details to register for the event. We are excited to share this innovative advancement in diabetes management with you and your team.

Thank you for your time and consideration. I look forward to the opportunity to connect with you at the webinar.

Best regards,

Albert Jones
Healthcare Innovations Inc.
[Your Contact Information]

### Step 3: Example 2

In [17]:
doc_name = "Laura Cox"

doc_email = "chris61@gmail.com"

template = """
At Healthcare Innovations Inc., we’re dedicated to improving healthcare delivery in the commercial sector by combining technology with patient-centered care. 
Since 2010, we’ve worked with healthcare providers, insurers, and pharma organizations to streamline workflows, enhance patient engagement, and drive better outcomes through innovative solutions like telemedicine, personalized tools, and data analytics. 
Our goal is simple: to make healthcare more accessible, efficient, and focused on the needs of patients. With a team of experts across medicine, tech, and business, we’re committed to transforming healthcare and improving lives, one solution at a time.
You are drafting an email for a sales representative in a healthcare company. 
The goal is to invite a healthcare provider to an educational webinar on a newly FDA-approved drug for diabetes management. 
The tone should be professional, compliant, and informative.

NOTE: Do not give Webinar Details. give the doctor name as the sender name 
{doctor_information}
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Invitation to Join Our Educational Webinar on a New FDA-Approved Diabetes Management Drug

Dear Dr. Cox,

I hope this message finds you well. I am writing to extend a cordial invitation to an upcoming educational webinar hosted by Healthcare Innovations Inc. We are excited to introduce a newly FDA-approved drug that represents a significant advancement in diabetes management.

This webinar will provide an excellent opportunity for healthcare providers to gain insights into the efficacy, safety, and potential benefits of this innovative treatment. Our expert panel will discuss clinical data, patient outcomes, and practical applications to enhance your practice.

We believe that your extensive experience in pediatrics and your commitment to patient-centered care make you an ideal participant for this informative session. Your insights and perspectives would be greatly valued.

Please let us know if you would be interested in attending, and we will be happy to provide additional details, including the date and time of the webinar.

Thank you for considering this opportunity to expand your knowledge and contribute to improving patient care.

Warm regards,

Dr. Laura Cox

### Step 4: Example 1:
#### Chain of Thought Prompting: A chain of thought is applied by breaking down the email drafting process into smaller thought steps, such as the email's objective, recipient, regulatory considerations, and effective communication strategies. These steps guide the model to generate more thoughtful and structured email content.

In [18]:
doc_name = "Albert Jones"

doc_email = "jerry19@yahoo.com"

template = """
Thought 1: What is the primary objective?

Need to write a sales email inviting healthcare providers to a webinar
Must be compliant with healthcare regulations
Focus is on education about new FDA-approved diabetes drug
Cannot include specific webinar details

Thought 2: Who is involved in this communication?

Sender: A doctor from Healthcare Innovations Inc.
Recipient: Healthcare providers (potential customers)
Context: Company has been in healthcare tech since 2010
Relationship: Professional, business-to-business communication

Thought 3: What regulatory considerations must be addressed?

Cannot make direct product claims
Must maintain FDA marketing compliance
Need to focus on educational value
Should avoid specific medical recommendations

Thought 4: What elements will make this email effective?

Professional tone establishes credibility
Educational focus rather than sales pitch
FDA approval mention adds legitimacy
Simple response mechanism encourages engagement

Thought 5: What potential concerns need to be avoided?

Aggressive sales language could deter healthcare professionals
Too much technical detail might overwhelm
Promotional content could violate regulations
Specific claims about outcomes must be avoided

NOTE: Do not give Webinar Details. give the doctor name as the sender name 

{doctor_information}
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Invitation to an Educational Webinar on Latest Diabetes Treatment

Dear Healthcare Professional,

I hope this message finds you well. My name is Dr. Albert Jones, and I am reaching out on behalf of Healthcare Innovations Inc. As a company dedicated to advancing healthcare technology since 2010, we are excited to invite you to an upcoming educational opportunity.

We are hosting an informative webinar that will delve into the science and application of a newly FDA-approved diabetes drug. This session is designed to provide you with valuable insights into the latest advancements and their implications for patient care.

While we are unable to share specific details about the webinar in this message, I assure you that it will be a comprehensive session aimed at enhancing your understanding of this significant development in diabetes treatment. Our goal is to foster an educational environment that supports your commitment to delivering high-quality healthcare.

If you are interested in participating or would like more information, please feel free to respond to this email or contact me directly. We are keen to facilitate a smooth and engaging experience for all attendees.

Thank you for your dedication to patient care and for considering this opportunity to expand your knowledge.

Warm regards,

Dr. Albert Jones
Healthcare Innovations Inc.
[Your Contact Information]

### Step 4: Example 2:

In [19]:
doc_name = "Donald Vaughan"

doc_email = "mccoycalvin@peterson.com"

template = """
Thought 1: What is the primary objective?

Need to write a sales email inviting healthcare providers to a webinar
Must be compliant with healthcare regulations
Focus is on education about new FDA-approved diabetes drug
Cannot include specific webinar details

Thought 2: Who is involved in this communication?

Sender: A doctor from Healthcare Innovations Inc.
Recipient: Healthcare providers (potential customers)
Context: Company has been in healthcare tech since 2010
Relationship: Professional, business-to-business communication

Thought 3: What regulatory considerations must be addressed?

Cannot make direct product claims
Must maintain FDA marketing compliance
Need to focus on educational value
Should avoid specific medical recommendations

Thought 4: What elements will make this email effective?

Professional tone establishes credibility
Educational focus rather than sales pitch
FDA approval mention adds legitimacy
Simple response mechanism encourages engagement

Thought 5: What potential concerns need to be avoided?

Aggressive sales language could deter healthcare professionals
Too much technical detail might overwhelm
Promotional content could violate regulations
Specific claims about outcomes must be avoided

NOTE: Do not give Webinar Details. give the doctor name as the sender name 

{doctor_information}
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Invitation to an Exclusive Educational Webinar on New Diabetes Treatment

Dear Dr. Vaughan,

I hope this message finds you well. As a fellow healthcare professional dedicated to advancing patient care, I am excited to extend a personal invitation to an upcoming educational webinar hosted by Healthcare Innovations Inc.

In our continuous effort to provide valuable educational resources to healthcare providers, this webinar will focus on a newly FDA-approved treatment for diabetes. This session is designed to enhance your understanding of this innovative therapy, ensuring you are well-informed about the latest advancements in diabetes management.

Key Highlights:
- Gain insights from leading experts in the field
- Understand the scientific foundations and clinical implications of the new treatment
- Explore how this innovation could fit into your practice

Healthcare Innovations Inc., founded in 2010, has been at the forefront of healthcare technology, committed to delivering educational content that adheres to FDA marketing compliance and regulations. We believe in providing knowledge that empowers you to make informed decisions for your patients, without making direct product claims or medical recommendations.

If you are interested in attending this educational opportunity, please reply to this email for more information on how to register.

Thank you for your dedication to patient care and your interest in staying informed about the latest developments in healthcare. We look forward to your participation.

Warm regards,

Dr. [Your Name]
Healthcare Innovations Inc.
[Your Email Address]
[Your Contact Information]

Please note that this email avoids specific medical recommendations, aggressive sales language, and promotional content to ensure compliance with healthcare regulations.

### Step 5:
#### Few-Shot: A set of example emails is included in the template to guide the model on how to construct a compliant and informative email. These examples provide the model with context on structure, tone, and language, ensuring the output aligns with the desired outcome.

### Example 1:

In [20]:
doc_name = "Albert Jones"

doc_email = "jerry19@yahoo.com"

template = """
At Healthcare Innovations Inc., we’re dedicated to improving healthcare delivery in the commercial sector by combining technology with patient-centered care. 
Since 2010, we’ve worked with healthcare providers, insurers, and pharma organizations to streamline workflows, enhance patient engagement, and drive better outcomes through innovative solutions like telemedicine, personalized tools, and data analytics. 
Our goal is simple: to make healthcare more accessible, efficient, and focused on the needs of patients. With a team of experts across medicine, tech, and business, we’re committed to transforming healthcare and improving lives, one solution at a time.
You are drafting an email for a sales representative in a healthcare company. 
The goal is to invite a healthcare provider to an educational webinar on a newly FDA-approved drug for diabetes management. 
The tone should be professional, compliant, and informative.

NOTE: Do not give Webinar Details. give the doctor name as the sender name 
{doctor_information}

Example:
Name=Peter Lewis, Email=robert27@gonzalez-benjamin.info
response=Subject: Discover Cutting-Edge Advancements in Diabetes Treatment
Dear Healthcare Professional,
I hope this message reaches you in good health and high spirits. My name is Peter Lewis, and I represent Healthcare Innovations Inc., a company at the forefront of healthcare technology since 2010.
We are thrilled to invite you to an upcoming webinar focused on the latest FDA-approved advancements in diabetes care. This session will highlight groundbreaking therapies and innovative approaches that can transform patient outcomes.
Our aim is to equip you with up-to-date, actionable knowledge that aligns with FDA regulations and enhances your practice. This educational opportunity is perfect for those committed to staying ahead in the ever-evolving field of diabetes management.
If this piques your interest, please reply to this email, and I’ll gladly provide additional details on how to join the session.
Thank you for your unwavering commitment to improving patient care. I look forward to the possibility of welcoming you to this enriching event.
Best regards,
Peter Lewis
Healthcare Innovations Inc.
[robert27@gonzalez-benjamin.info]
+1-627-300-0235

Name=Stephanie Christensen, Email=larry21@hotmail.com
response=Subject: Enhance Your Expertise in Diabetes Care
Dear Healthcare Provider,
I trust this message finds you well. My name is Stephanie Christensen, and I’m reaching out from Healthcare Innovations Inc., a trusted leader in healthcare solutions for over a decade.
We are excited to offer you the chance to participate in a specialized webinar focusing on new, FDA-approved treatments for diabetes. This engaging session is designed to explore emerging therapies and provide practical insights that you can apply directly in your practice.
At Healthcare Innovations Inc., we prioritize sharing accurate and reliable information to support healthcare professionals in delivering exceptional patient care. This webinar will equip you with the latest knowledge to stay at the forefront of diabetes treatment advancements.
If you’re interested in joining us, simply respond to this email, and I’ll be happy to provide further details about the event.
Thank you for your dedication to advancing medical care. I hope to connect with you at the webinar.
Warm regards,
Stephanie Christensen
Healthcare Innovations Inc.
[larry21@hotmail.com]
766-701-7097
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Name=Albert Jones, Email=jerry19@yahoo.com
response=Subject: Join Us for an Educational Webinar on Diabetes Management

Dear Healthcare Provider,

I hope this email finds you well. My name is Albert Jones, and I am contacting you on behalf of Healthcare Innovations Inc., a leader in integrating technology with patient-centered care since 2010.

We are pleased to invite you to an informative webinar that will delve into the latest FDA-approved advancements in diabetes management. This session will shed light on innovative therapies and cutting-edge approaches designed to improve patient outcomes in diabetes care.

Our objective is to provide you with valuable, compliant insights that can enhance your clinical practice. This educational opportunity is tailored for healthcare professionals who are eager to stay informed about the latest developments in diabetes treatment.

If you are interested in attending, please reply to this email, and I will be happy to send you further details on how to participate in this enriching event.

Thank you for your commitment to delivering high-quality patient care. We look forward to the opportunity to welcome you to this webinar.

Best regards,

Albert Jones
Healthcare Innovations Inc.
[jerry19@yahoo.com]
+1-083-768-2335x11893

### Step 5: Example 2:

In [21]:
doc_name = "Alison Flowers"

doc_email = "vrobinson@flynn.com"

template = """
At Healthcare Innovations Inc., we’re dedicated to improving healthcare delivery in the commercial sector by combining technology with patient-centered care. 
Since 2010, we’ve worked with healthcare providers, insurers, and pharma organizations to streamline workflows, enhance patient engagement, and drive better outcomes through innovative solutions like telemedicine, personalized tools, and data analytics. 
Our goal is simple: to make healthcare more accessible, efficient, and focused on the needs of patients. With a team of experts across medicine, tech, and business, we’re committed to transforming healthcare and improving lives, one solution at a time.
You are drafting an email for a sales representative in a healthcare company. 
The goal is to invite a healthcare provider to an educational webinar on a newly FDA-approved drug for diabetes management. 
The tone should be professional, compliant, and informative.

NOTE: Do not give Webinar Details. give the doctor name as the sender name 
{doctor_information}

Example:
Name=Peter Lewis, Email=robert27@gonzalez-benjamin.info
response=Subject: Discover Cutting-Edge Advancements in Diabetes Treatment
Dear Healthcare Professional,
I hope this message reaches you in good health and high spirits. My name is Peter Lewis, and I represent Healthcare Innovations Inc., a company at the forefront of healthcare technology since 2010.
We are thrilled to invite you to an upcoming webinar focused on the latest FDA-approved advancements in diabetes care. This session will highlight groundbreaking therapies and innovative approaches that can transform patient outcomes.
Our aim is to equip you with up-to-date, actionable knowledge that aligns with FDA regulations and enhances your practice. This educational opportunity is perfect for those committed to staying ahead in the ever-evolving field of diabetes management.
If this piques your interest, please reply to this email, and I’ll gladly provide additional details on how to join the session.
Thank you for your unwavering commitment to improving patient care. I look forward to the possibility of welcoming you to this enriching event.
Best regards,
Peter Lewis
Healthcare Innovations Inc.
[robert27@gonzalez-benjamin.info]
+1-627-300-0235

Name=Stephanie Christensen, Email=larry21@hotmail.com
response=Subject: Enhance Your Expertise in Diabetes Care
Dear Healthcare Provider,
I trust this message finds you well. My name is Stephanie Christensen, and I’m reaching out from Healthcare Innovations Inc., a trusted leader in healthcare solutions for over a decade.
We are excited to offer you the chance to participate in a specialized webinar focusing on new, FDA-approved treatments for diabetes. This engaging session is designed to explore emerging therapies and provide practical insights that you can apply directly in your practice.
At Healthcare Innovations Inc., we prioritize sharing accurate and reliable information to support healthcare professionals in delivering exceptional patient care. This webinar will equip you with the latest knowledge to stay at the forefront of diabetes treatment advancements.
If you’re interested in joining us, simply respond to this email, and I’ll be happy to provide further details about the event.
Thank you for your dedication to advancing medical care. I hope to connect with you at the webinar.
Warm regards,
Stephanie Christensen
Healthcare Innovations Inc.
[larry21@hotmail.com]
766-701-7097
"""

prompt = template.format(doctor_information=get_HCP_data(doc_name, doc_email))

chain = llm | StrOutputParser()

result = chain.invoke([prompt])

print(result)

Subject: Unlock New Possibilities in Diabetes Management

Dear Healthcare Provider,

I hope this message finds you in good health and high spirits. My name is Alison Flowers, and I represent Healthcare Innovations Inc., a pioneer in integrating technology with patient-centered care since 2010.

We are pleased to invite you to an exclusive webinar spotlighting the latest FDA-approved drug for diabetes management. This educational session will delve into innovative treatments and strategies aimed at enhancing patient outcomes and streamlining care.

Our commitment at Healthcare Innovations Inc. is to furnish healthcare professionals with cutting-edge, compliant knowledge to advance your practice. This webinar provides an excellent opportunity to deepen your expertise in diabetes management and stay informed about transformative therapies.

If this opportunity interests you, please reply to this email, and I will be delighted to share more information about how to participate in this informative event.

Thank you for your continued commitment to excellence in patient care. I look forward to the possibility of engaging with you at the webinar.

Best regards,

Alison Flowers
Healthcare Innovations Inc.
[vrobinson@flynn.com]
390.565.8628

# Conclusion: Email Drafting Process for Healthcare Webinar Invitation
## Explanation:
- Purpose: Demonstrate the process of generating an email for inviting healthcare providers to a webinar, using dynamic content and contextual information to ensure the email is professional and compliant.
## Code Overview:
### 1. Define the Email Template:
- template = """...""": The email template is created with placeholders for dynamic information (e.g., doctor’s name and email).
The template ensures the email has a professional tone, is informative, and compliant with healthcare regulations.
### 2. Generate the Email:
- chain.invoke([prompt]): This function is used to generate the email by invoking the model with the template and filling in the dynamic content (doctor's information).
- The model processes the template, applying contextual information such as the company’s mission and regulatory guidelines to generate the email.
### 3. Enhance with Context:
- The email generation is enhanced by providing additional context, such as the company’s background, to make the email more personalized and engaging for the recipient.
### 4. Zero-Shot and Few-Shot Learning:
- Zero-Shot: The model generates the email without prior examples, guided solely by the template and provided context.
- Few-Shot: Example emails are included to guide the model in structuring the response, ensuring consistency in tone and format.

## Output:
- Generated Email: A well-crafted, professional email inviting healthcare providers to a webinar about a new FDA-approved drug, tailored to comply with healthcare regulations.
- This process demonstrates how a dynamic, contextually informed email can be generated using a template-based approach, ensuring compliance and professionalism in healthcare communications.